module4-task1 completed
htmlacademy-javascript/1801367-kekstagram-23 pull request #3
Opened 2021-06-05 14:30 UTC by siberian-dm

2021-06-07 14:46 UTC, ademaro requested changes
Реализация интересная, но очень не оптимальная... может, через `for (let i = 0; i < 25; I++) { ... }` хотя бы сделаем? Если что — предлагаю созвониться))

2021-06-07 14:46 UTC, ademaro commented on js/main.js
> +const FAKE_COMMENTS = [
FAKE_ — такой префикс лишний)

2021-06-07 14:46 UTC, ademaro commented on js/main.js
> +// };
если код не нужен — удаляем, а не комментим)

2021-06-07 14:46 UTC, ademaro commented on js/main.js
>  const getRandomInteger = function (firstNumber, secondNumber) {
jsDoc?

2021-06-07 14:46 UTC, ademaro commented on js/main.js
> +const usedNumber = [];
внутрь ф-ции

2021-06-07 14:59 UTC, siberian-dm commented on js/main.js
> +// };
это функция из первого задания, тут она не пригодилась просто)

2021-06-07 15:04 UTC, siberian-dm commented
> Реализация интересная, но очень не оптимальная... может, через `for (let i = 0; i < 25; I++) { ... }` хотя бы сделаем? Если что — предлагаю созвониться))

ок,  в какое время?

2021-06-07 15:43 UTC, siberian-dm commented
>` for (let i = 0; i < 25; I++) { ... }`

слушай, перечитал еще раз задание, и только сейчас дошло. что нигде не указано, что идентификаторы должны быть сгенерированы рандомайзером, также как и URL...)))

2021-06-07 15:45 UTC, siberian-dm commented on js/main.js
>  const getRandomInteger = function (firstNumber, secondNumber) {
директорию с документацией тоже в проект пушить? или только комменты в коде в этом формате? просто я еще в slack это спрашивал, ты не ответил, я по этому и не стал оставлять эти комменты

2021-06-10 12:25 UTC, ademaro commented on js/main.js
>  const getRandomInteger = function (firstNumber, secondNumber) {
jsDoc — вторая строчка (и следующие) — с дополнительным пробелом должны быть (следующие звёздочки под первой звездой на первой строке под ней сразу)

2021-06-10 12:25 UTC, ademaro approved these changes
Отлично, летим дальше

2021-06-10 12:25 UTC, merged

2021-06-10 12:26 UTC, ademaro commented on js/main.js
> +const similiarPhotos = new Array(PHOTO_COUNT).fill(null).map(createPhoto);
как вариант — создание массива фотографий — в отдельную ф-цию можем вынести для удобства

2021-06-10 12:32 UTC, siberian-dm commented on js/main.js
> +const similiarPhotos = new Array(PHOTO_COUNT).fill(null).map(createPhoto);
в следующий пуллреквест тогда уже в виде функции сделаю

2021-06-10 12:49 UTC, siberian-dm commented on js/main.js
>  const getRandomInteger = function (firstNumber, secondNumber) {
/**
   *
   *
   *
   */

вот это ты имеешь в виду?